gen.o: gen.c ../SDCCglobl.h ../SDCCset.h ../../sdccconf.h ../SDCCerr.h \
 ../../support/Util/newalloc.h ../../support/Util/dbuf_string.h \
 ../../support/Util/dbuf.h ../common.h ../SDCCglobl.h ../SDCCmem.h \
 ../../support/Util/dbuf.h ../SDCCast.h ../SDCCsymt.h ../SDCChasht.h \
 ../SDCCval.h ../SDCCy.h ../SDCCbitv.h ../SDCCicode.h ../SDCClabel.h \
 ../SDCCBBlock.h ../SDCCloop.h ../SDCCcse.h ../SDCCcflow.h ../SDCCdflow.h \
 ../SDCClrange.h ../SDCCptropt.h ../SDCCopt.h ../SDCCglue.h \
 ../SDCCpeeph.h ../SDCCdebug.h ../SDCCutil.h ../SDCCasm.h ../port.h \
 ../SDCCargs.h ../mcs51/peep.h main.h ralloc.h ../SDCCicode.h \
 ../SDCCBBlock.h gen.h
ralloc.o: ralloc.c ../common.h ../SDCCglobl.h ../SDCCset.h \
 ../../sdccconf.h ../SDCCerr.h ../SDCCmem.h ../../support/Util/dbuf.h \
 ../SDCCast.h ../SDCCsymt.h ../SDCChasht.h ../SDCCval.h ../SDCCy.h \
 ../SDCCbitv.h ../SDCCicode.h ../SDCClabel.h ../SDCCBBlock.h \
 ../SDCCloop.h ../SDCCcse.h ../SDCCcflow.h ../SDCCdflow.h ../SDCClrange.h \
 ../SDCCptropt.h ../SDCCopt.h ../SDCCglue.h ../SDCCpeeph.h ../SDCCdebug.h \
 ../SDCCutil.h ../SDCCasm.h ../port.h ../SDCCargs.h ../mcs51/peep.h \
 ../../support/Util/newalloc.h ralloc.h ../SDCCicode.h ../SDCCBBlock.h \
 gen.h
main.o: main.c ../common.h ../SDCCglobl.h ../SDCCset.h ../../sdccconf.h \
 ../SDCCerr.h ../SDCCmem.h ../../support/Util/dbuf.h ../SDCCast.h \
 ../SDCCsymt.h ../SDCChasht.h ../SDCCval.h ../SDCCy.h ../SDCCbitv.h \
 ../SDCCicode.h ../SDCClabel.h ../SDCCBBlock.h ../SDCCloop.h ../SDCCcse.h \
 ../SDCCcflow.h ../SDCCdflow.h ../SDCClrange.h ../SDCCptropt.h \
 ../SDCCopt.h ../SDCCglue.h ../SDCCpeeph.h ../SDCCdebug.h ../SDCCutil.h \
 ../SDCCasm.h ../port.h ../SDCCargs.h ../mcs51/peep.h \
 ../../support/Util/newalloc.h main.h ralloc.h ../SDCCicode.h \
 ../SDCCBBlock.h gen.h ../../support/Util/BuildCmd.h \
 ../../support/Util/MySystem.h ../SDCCset.h \
 ../../support/Util/dbuf_string.h ../../support/Util/dbuf.h ../SDCCutil.h \
 ../SDCCglobl.h peeph.rul
