asmain.o: asmain.c asm.h ../../sdccconf.h
assubr.o: assubr.c asm.h ../../sdccconf.h
asexpr.o: asexpr.c asm.h ../../sdccconf.h
asdata.o: asdata.c asm.h ../../sdccconf.h
aslist.o: aslist.c asm.h ../../sdccconf.h
asout.o: asout.c asm.h ../../sdccconf.h
i51ext.o: i51ext.c asm.h ../../sdccconf.h i8051.h
i51pst.o: i51pst.c asm.h ../../sdccconf.h i8051.h
i51mch.o: i51mch.c asm.h ../../sdccconf.h i8051.h
i51adr.o: i51adr.c asm.h ../../sdccconf.h i8051.h
strcmpi.o: ../asxxsrc/strcmpi.c
assym.o: ../asxxsrc/assym.c asm.h ../../sdccconf.h
aslex.o: ../asxxsrc/aslex.c ../../support/Util/dbuf_string.h \
 ../../support/Util/dbuf.h asm.h ../../sdccconf.h
asnoice.o: ../asxxsrc/asnoice.c asm.h ../../sdccconf.h
dbuf.o: ../../support/Util/dbuf.c ../../support/Util/dbuf.h
dbuf_string.o: ../../support/Util/dbuf_string.c \
 ../../support/Util/dbuf_string.h ../../support/Util/dbuf.h
