glue.o: glue.c ../common.h ../SDCCglobl.h ../SDCCset.h ../../sdccconf.h \
 ../SDCCerr.h ../SDCCmem.h ../../support/Util/dbuf.h ../SDCCast.h \
 ../SDCCsymt.h ../SDCChasht.h ../SDCCval.h ../SDCCy.h ../SDCCbitv.h \
 ../SDCCicode.h ../SDCClabel.h ../SDCCBBlock.h ../SDCCloop.h ../SDCCcse.h \
 ../SDCCcflow.h ../SDCCdflow.h ../SDCClrange.h ../SDCCptropt.h \
 ../SDCCopt.h ../SDCCglue.h ../SDCCpeeph.h ../SDCCdebug.h ../SDCCutil.h \
 ../SDCCasm.h ../port.h ../SDCCargs.h ../mcs51/peep.h \
 ../../support/Util/newalloc.h ralloc.h ../SDCCicode.h ../SDCCbitv.h \
 ../SDCCset.h ../SDCCBBlock.h pcoderegs.h pcode.h gen.h main.h device.h \
 ../../support/Util/dbuf_string.h ../../support/Util/dbuf.h
pcodepeep.o: pcodepeep.c ../common.h ../SDCCglobl.h ../SDCCset.h \
 ../../sdccconf.h ../SDCCerr.h ../SDCCmem.h ../../support/Util/dbuf.h \
 ../SDCCast.h ../SDCCsymt.h ../SDCChasht.h ../SDCCval.h ../SDCCy.h \
 ../SDCCbitv.h ../SDCCicode.h ../SDCClabel.h ../SDCCBBlock.h \
 ../SDCCloop.h ../SDCCcse.h ../SDCCcflow.h ../SDCCdflow.h ../SDCClrange.h \
 ../SDCCptropt.h ../SDCCopt.h ../SDCCglue.h ../SDCCpeeph.h ../SDCCdebug.h \
 ../SDCCutil.h ../SDCCasm.h ../port.h ../SDCCargs.h ../mcs51/peep.h \
 ../../support/Util/newalloc.h pcode.h pcodeflow.h ralloc.h \
 ../SDCCicode.h ../SDCCBBlock.h pcoderegs.h
pcoderegs.o: pcoderegs.c ../common.h ../SDCCglobl.h ../SDCCset.h \
 ../../sdccconf.h ../SDCCerr.h ../SDCCmem.h ../../support/Util/dbuf.h \
 ../SDCCast.h ../SDCCsymt.h ../SDCChasht.h ../SDCCval.h ../SDCCy.h \
 ../SDCCbitv.h ../SDCCicode.h ../SDCClabel.h ../SDCCBBlock.h \
 ../SDCCloop.h ../SDCCcse.h ../SDCCcflow.h ../SDCCdflow.h ../SDCClrange.h \
 ../SDCCptropt.h ../SDCCopt.h ../SDCCglue.h ../SDCCpeeph.h ../SDCCdebug.h \
 ../SDCCutil.h ../SDCCasm.h ../port.h ../SDCCargs.h ../mcs51/peep.h \
 ../../support/Util/newalloc.h ralloc.h ../SDCCicode.h ../SDCCBBlock.h \
 pcoderegs.h device.h pcode.h pcodeflow.h main.h
pcode.o: pcode.c ../common.h ../SDCCglobl.h ../SDCCset.h ../../sdccconf.h \
 ../SDCCerr.h ../SDCCmem.h ../../support/Util/dbuf.h ../SDCCast.h \
 ../SDCCsymt.h ../SDCChasht.h ../SDCCval.h ../SDCCy.h ../SDCCbitv.h \
 ../SDCCicode.h ../SDCClabel.h ../SDCCBBlock.h ../SDCCloop.h ../SDCCcse.h \
 ../SDCCcflow.h ../SDCCdflow.h ../SDCClrange.h ../SDCCptropt.h \
 ../SDCCopt.h ../SDCCglue.h ../SDCCpeeph.h ../SDCCdebug.h ../SDCCutil.h \
 ../SDCCasm.h ../port.h ../SDCCargs.h ../mcs51/peep.h \
 ../../support/Util/newalloc.h pcode.h pcodeflow.h ralloc.h \
 ../SDCCicode.h ../SDCCBBlock.h pcoderegs.h device.h
device.o: device.c ../common.h ../SDCCglobl.h ../SDCCset.h \
 ../../sdccconf.h ../SDCCerr.h ../SDCCmem.h ../../support/Util/dbuf.h \
 ../SDCCast.h ../SDCCsymt.h ../SDCChasht.h ../SDCCval.h ../SDCCy.h \
 ../SDCCbitv.h ../SDCCicode.h ../SDCClabel.h ../SDCCBBlock.h \
 ../SDCCloop.h ../SDCCcse.h ../SDCCcflow.h ../SDCCdflow.h ../SDCClrange.h \
 ../SDCCptropt.h ../SDCCopt.h ../SDCCglue.h ../SDCCpeeph.h ../SDCCdebug.h \
 ../SDCCutil.h ../SDCCasm.h ../port.h ../SDCCargs.h ../mcs51/peep.h \
 ../../support/Util/newalloc.h main.h pcode.h ralloc.h ../SDCCicode.h \
 ../SDCCBBlock.h pcoderegs.h device.h
gen.o: gen.c ../SDCCglobl.h ../SDCCset.h ../../sdccconf.h ../SDCCerr.h \
 ../../support/Util/newalloc.h ../common.h ../SDCCglobl.h ../SDCCmem.h \
 ../../support/Util/dbuf.h ../SDCCast.h ../SDCCsymt.h ../SDCChasht.h \
 ../SDCCval.h ../SDCCy.h ../SDCCbitv.h ../SDCCicode.h ../SDCClabel.h \
 ../SDCCBBlock.h ../SDCCloop.h ../SDCCcse.h ../SDCCcflow.h ../SDCCdflow.h \
 ../SDCClrange.h ../SDCCptropt.h ../SDCCopt.h ../SDCCglue.h \
 ../SDCCpeeph.h ../SDCCdebug.h ../SDCCutil.h ../SDCCasm.h ../port.h \
 ../SDCCargs.h ../mcs51/peep.h ../SDCCpeeph.h ralloc.h ../SDCCicode.h \
 ../SDCCBBlock.h pcoderegs.h pcode.h gen.h glue.h ../SDCCset.h
ralloc.o: ralloc.c ../common.h ../SDCCglobl.h ../SDCCset.h \
 ../../sdccconf.h ../SDCCerr.h ../SDCCmem.h ../../support/Util/dbuf.h \
 ../SDCCast.h ../SDCCsymt.h ../SDCChasht.h ../SDCCval.h ../SDCCy.h \
 ../SDCCbitv.h ../SDCCicode.h ../SDCClabel.h ../SDCCBBlock.h \
 ../SDCCloop.h ../SDCCcse.h ../SDCCcflow.h ../SDCCdflow.h ../SDCClrange.h \
 ../SDCCptropt.h ../SDCCopt.h ../SDCCglue.h ../SDCCpeeph.h ../SDCCdebug.h \
 ../SDCCutil.h ../SDCCasm.h ../port.h ../SDCCargs.h ../mcs51/peep.h \
 ../../support/Util/newalloc.h ralloc.h ../SDCCicode.h ../SDCCBBlock.h \
 pcoderegs.h device.h pcode.h gen.h
main.o: main.c ../common.h ../SDCCglobl.h ../SDCCset.h ../../sdccconf.h \
 ../SDCCerr.h ../SDCCmem.h ../../support/Util/dbuf.h ../SDCCast.h \
 ../SDCCsymt.h ../SDCChasht.h ../SDCCval.h ../SDCCy.h ../SDCCbitv.h \
 ../SDCCicode.h ../SDCClabel.h ../SDCCBBlock.h ../SDCCloop.h ../SDCCcse.h \
 ../SDCCcflow.h ../SDCCdflow.h ../SDCClrange.h ../SDCCptropt.h \
 ../SDCCopt.h ../SDCCglue.h ../SDCCpeeph.h ../SDCCdebug.h ../SDCCutil.h \
 ../SDCCasm.h ../port.h ../SDCCargs.h ../mcs51/peep.h \
 ../../support/Util/newalloc.h main.h ralloc.h ../SDCCicode.h \
 ../SDCCBBlock.h pcoderegs.h device.h ../SDCCutil.h ../SDCCmacro.h \
 ../../support/Util/MySystem.h ../SDCCset.h glue.h ../SDCCset.h \
 ../../support/Util/dbuf_string.h ../../support/Util/dbuf.h peeph.rul
genarith.o: genarith.c ../SDCCglobl.h ../SDCCset.h ../../sdccconf.h \
 ../SDCCerr.h ../../support/Util/newalloc.h ../common.h ../SDCCglobl.h \
 ../SDCCmem.h ../../support/Util/dbuf.h ../SDCCast.h ../SDCCsymt.h \
 ../SDCChasht.h ../SDCCval.h ../SDCCy.h ../SDCCbitv.h ../SDCCicode.h \
 ../SDCClabel.h ../SDCCBBlock.h ../SDCCloop.h ../SDCCcse.h ../SDCCcflow.h \
 ../SDCCdflow.h ../SDCClrange.h ../SDCCptropt.h ../SDCCopt.h \
 ../SDCCglue.h ../SDCCpeeph.h ../SDCCdebug.h ../SDCCutil.h ../SDCCasm.h \
 ../port.h ../SDCCargs.h ../mcs51/peep.h ../SDCCpeeph.h ralloc.h \
 ../SDCCicode.h ../SDCCBBlock.h pcoderegs.h pcode.h gen.h
pcodeflow.o: pcodeflow.c ../common.h ../SDCCglobl.h ../SDCCset.h \
 ../../sdccconf.h ../SDCCerr.h ../SDCCmem.h ../../support/Util/dbuf.h \
 ../SDCCast.h ../SDCCsymt.h ../SDCChasht.h ../SDCCval.h ../SDCCy.h \
 ../SDCCbitv.h ../SDCCicode.h ../SDCClabel.h ../SDCCBBlock.h \
 ../SDCCloop.h ../SDCCcse.h ../SDCCcflow.h ../SDCCdflow.h ../SDCClrange.h \
 ../SDCCptropt.h ../SDCCopt.h ../SDCCglue.h ../SDCCpeeph.h ../SDCCdebug.h \
 ../SDCCutil.h ../SDCCasm.h ../port.h ../SDCCargs.h ../mcs51/peep.h \
 ../../support/Util/newalloc.h ralloc.h ../SDCCicode.h ../SDCCBBlock.h \
 pcoderegs.h device.h pcode.h pcodeflow.h
